// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/auth/types/types.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace clarifai {
namespace auth {
namespace types {

enum AuthType : int {
  undef = 0,
  NoAuth = 1,
  KeyAuth = 2,
  SessionTokenAuth = 3,
  AdminAuth = 4,
  PATAuth = 5,
  AuthType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  AuthType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool AuthType_IsValid(int value);
constexpr AuthType AuthType_MIN = undef;
constexpr AuthType AuthType_MAX = PATAuth;
constexpr int AuthType_ARRAYSIZE = AuthType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* AuthType_descriptor();
template<typename T>
inline const std::string& AuthType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AuthType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AuthType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    AuthType_descriptor(), enum_t_value);
}
inline bool AuthType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AuthType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<AuthType>(
    AuthType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace types
}  // namespace auth
}  // namespace clarifai

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::clarifai::auth::types::AuthType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::clarifai::auth::types::AuthType>() {
  return ::clarifai::auth::types::AuthType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto
