// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/auth/util/extension.proto

#include "proto/clarifai/auth/util/extension.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace clarifai {
namespace auth {
namespace util {
}  // namespace util
}  // namespace auth
}  // namespace clarifai
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_proto_2fclarifai_2fauth_2futil_2fextension_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fclarifai_2fauth_2futil_2fextension_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fclarifai_2fauth_2futil_2fextension_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fclarifai_2fauth_2futil_2fextension_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_proto_2fclarifai_2fauth_2futil_2fextension_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n(proto/clarifai/auth/util/extension.pro"
  "to\022\022clarifai.auth.util\032%proto/clarifai/a"
  "uth/scope/scope.proto\032%proto/clarifai/au"
  "th/types/types.proto\032 google/protobuf/de"
  "scriptor.proto:9\n\020cl_private_field\022\035.goo"
  "gle.protobuf.FieldOptions\030\300\363\004 \001(\010:8\n\016cl_"
  "private_rpc\022\036.google.protobuf.MethodOpti"
  "ons\030\301\363\004 \001(\010:U\n\023cl_depending_scopes\022\036.goo"
  "gle.protobuf.MethodOptions\030\302\363\004 \003(\0162\026.cla"
  "rifai.auth.scope.S:U\n\014cl_auth_type\022\036.goo"
  "gle.protobuf.MethodOptions\030\303\363\004 \001(\0162\035.cla"
  "rifai.auth.types.AuthType:=\n\022cl_private_"
  "message\022\037.google.protobuf.MessageOptions"
  "\030\304\363\004 \001(\010B\236\001\n\033com.clarifai.grpc.auth.util"
  "P\001Zvgithub.com/Clarifai/clarifai-go-grpc"
  "/proto/clarifai/auth/github.com/Clarifai"
  "/clarifai-go-grpc/proto/clarifai/auth/ut"
  "il\242\002\004CAIPb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_deps[3] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
  &::descriptor_table_proto_2fclarifai_2fauth_2fscope_2fscope_2eproto,
  &::descriptor_table_proto_2fclarifai_2fauth_2ftypes_2ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_once;
static bool descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto = {
  &descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_initialized, descriptor_table_protodef_proto_2fclarifai_2fauth_2futil_2fextension_2eproto, "proto/clarifai/auth/util/extension.proto", 697,
  &descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_once, descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_sccs, descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto_deps, 0, 3,
  schemas, file_default_instances, TableStruct_proto_2fclarifai_2fauth_2futil_2fextension_2eproto::offsets,
  file_level_metadata_proto_2fclarifai_2fauth_2futil_2fextension_2eproto, 0, file_level_enum_descriptors_proto_2fclarifai_2fauth_2futil_2fextension_2eproto, file_level_service_descriptors_proto_2fclarifai_2fauth_2futil_2fextension_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fclarifai_2fauth_2futil_2fextension_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto), true);
namespace clarifai {
namespace auth {
namespace util {
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  cl_private_field(kClPrivateFieldFieldNumber, false);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  cl_private_rpc(kClPrivateRpcFieldNumber, false);
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::RepeatedEnumTypeTraits< ::clarifai::auth::scope::S, ::clarifai::auth::scope::S_IsValid>, 14, false >
  cl_depending_scopes(kClDependingScopesFieldNumber, static_cast< ::clarifai::auth::scope::S >(0));
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::EnumTypeTraits< ::clarifai::auth::types::AuthType, ::clarifai::auth::types::AuthType_IsValid>, 14, false >
  cl_auth_type(kClAuthTypeFieldNumber, static_cast< ::clarifai::auth::types::AuthType >(0));
::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  cl_private_message(kClPrivateMessageFieldNumber, false);

// @@protoc_insertion_point(namespace_scope)
}  // namespace util
}  // namespace auth
}  // namespace clarifai
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
