// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/status/status.proto

#include "proto/clarifai/api/status/status.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace clarifai {
namespace api {
namespace status {
PROTOBUF_CONSTEXPR Status::Status(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.stack_trace_)*/{}
  , /*decltype(_impl_.description_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.details_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.req_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.internal_details_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.redirect_info_)*/nullptr
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_.percent_completed_)*/0u
  , /*decltype(_impl_.time_remaining_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StatusDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StatusDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StatusDefaultTypeInternal() {}
  union {
    Status _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StatusDefaultTypeInternal _Status_default_instance_;
PROTOBUF_CONSTEXPR RedirectInfo::RedirectInfo(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.url_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.resource_type_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.old_resource_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.new_resource_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RedirectInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RedirectInfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RedirectInfoDefaultTypeInternal() {}
  union {
    RedirectInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RedirectInfoDefaultTypeInternal _RedirectInfo_default_instance_;
PROTOBUF_CONSTEXPR BaseResponse::BaseResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.status_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BaseResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BaseResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BaseResponseDefaultTypeInternal() {}
  union {
    BaseResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BaseResponseDefaultTypeInternal _BaseResponse_default_instance_;
}  // namespace status
}  // namespace api
}  // namespace clarifai
static ::_pb::Metadata file_level_metadata_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto[3];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto = nullptr;

const uint32_t TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.description_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.details_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.stack_trace_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.percent_completed_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.time_remaining_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.req_id_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.internal_details_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::Status, _impl_.redirect_info_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::RedirectInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::RedirectInfo, _impl_.url_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::RedirectInfo, _impl_.resource_type_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::RedirectInfo, _impl_.old_resource_id_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::RedirectInfo, _impl_.new_resource_id_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::BaseResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::status::BaseResponse, _impl_.status_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::clarifai::api::status::Status)},
  { 15, -1, -1, sizeof(::clarifai::api::status::RedirectInfo)},
  { 25, -1, -1, sizeof(::clarifai::api::status::BaseResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::clarifai::api::status::_Status_default_instance_._instance,
  &::clarifai::api::status::_RedirectInfo_default_instance_._instance,
  &::clarifai::api::status::_BaseResponse_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n&proto/clarifai/api/status/status.proto"
  "\022\023clarifai.api.status\032(proto/clarifai/au"
  "th/util/extension.proto\032+proto/clarifai/"
  "api/status/status_code.proto\"\233\002\n\006Status\022"
  "-\n\004code\030\001 \001(\0162\037.clarifai.api.status.Stat"
  "usCode\022\023\n\013description\030\002 \001(\t\022\017\n\007details\030\003"
  " \001(\t\022\031\n\013stack_trace\030\004 \003(\tB\004\200\234\'\001\022\031\n\021perce"
  "nt_completed\030\005 \001(\r\022\026\n\016time_remaining\030\006 \001"
  "(\r\022\016\n\006req_id\030\007 \001(\t\022\036\n\020internal_details\030\010"
  " \001(\tB\004\200\234\'\001\022>\n\rredirect_info\030\t \001(\0132!.clar"
  "ifai.api.status.RedirectInfoB\004\200\234\'\001\"d\n\014Re"
  "directInfo\022\013\n\003url\030\001 \001(\t\022\025\n\rresource_type"
  "\030\002 \001(\t\022\027\n\017old_resource_id\030\003 \001(\t\022\027\n\017new_r"
  "esource_id\030\004 \001(\t\";\n\014BaseResponse\022+\n\006stat"
  "us\030\001 \001(\0132\033.clarifai.api.status.StatusBg\n"
  "\034com.clarifai.grpc.api.statusP\001Z>github."
  "com/Clarifai/clarifai-go-grpc/proto/clar"
  "ifai/api/status\242\002\004CAIPb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_deps[2] = {
  &::descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_5fcode_2eproto,
  &::descriptor_table_proto_2fclarifai_2fauth_2futil_2fextension_2eproto,
};
static ::_pbi::once_flag descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto = {
    false, false, 710, descriptor_table_protodef_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto,
    "proto/clarifai/api/status/status.proto",
    &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_once, descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_deps, 2, 3,
    schemas, file_default_instances, TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto::offsets,
    file_level_metadata_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto, file_level_enum_descriptors_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto,
    file_level_service_descriptors_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_getter() {
  return &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto(&descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto);
namespace clarifai {
namespace api {
namespace status {

// ===================================================================

class Status::_Internal {
 public:
  static const ::clarifai::api::status::RedirectInfo& redirect_info(const Status* msg);
};

const ::clarifai::api::status::RedirectInfo&
Status::_Internal::redirect_info(const Status* msg) {
  return *msg->_impl_.redirect_info_;
}
Status::Status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.status.Status)
}
Status::Status(const Status& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Status* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.stack_trace_){from._impl_.stack_trace_}
    , decltype(_impl_.description_){}
    , decltype(_impl_.details_){}
    , decltype(_impl_.req_id_){}
    , decltype(_impl_.internal_details_){}
    , decltype(_impl_.redirect_info_){nullptr}
    , decltype(_impl_.code_){}
    , decltype(_impl_.percent_completed_){}
    , decltype(_impl_.time_remaining_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_description().empty()) {
    _this->_impl_.description_.Set(from._internal_description(), 
      _this->GetArenaForAllocation());
  }
  _impl_.details_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.details_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_details().empty()) {
    _this->_impl_.details_.Set(from._internal_details(), 
      _this->GetArenaForAllocation());
  }
  _impl_.req_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.req_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_req_id().empty()) {
    _this->_impl_.req_id_.Set(from._internal_req_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.internal_details_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.internal_details_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_internal_details().empty()) {
    _this->_impl_.internal_details_.Set(from._internal_internal_details(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_redirect_info()) {
    _this->_impl_.redirect_info_ = new ::clarifai::api::status::RedirectInfo(*from._impl_.redirect_info_);
  }
  ::memcpy(&_impl_.code_, &from._impl_.code_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.time_remaining_) -
    reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.time_remaining_));
  // @@protoc_insertion_point(copy_constructor:clarifai.api.status.Status)
}

inline void Status::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.stack_trace_){arena}
    , decltype(_impl_.description_){}
    , decltype(_impl_.details_){}
    , decltype(_impl_.req_id_){}
    , decltype(_impl_.internal_details_){}
    , decltype(_impl_.redirect_info_){nullptr}
    , decltype(_impl_.code_){0}
    , decltype(_impl_.percent_completed_){0u}
    , decltype(_impl_.time_remaining_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.description_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.description_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.details_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.details_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.req_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.req_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.internal_details_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.internal_details_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Status::~Status() {
  // @@protoc_insertion_point(destructor:clarifai.api.status.Status)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Status::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.stack_trace_.~RepeatedPtrField();
  _impl_.description_.Destroy();
  _impl_.details_.Destroy();
  _impl_.req_id_.Destroy();
  _impl_.internal_details_.Destroy();
  if (this != internal_default_instance()) delete _impl_.redirect_info_;
}

void Status::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Status::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.status.Status)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.stack_trace_.Clear();
  _impl_.description_.ClearToEmpty();
  _impl_.details_.ClearToEmpty();
  _impl_.req_id_.ClearToEmpty();
  _impl_.internal_details_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.redirect_info_ != nullptr) {
    delete _impl_.redirect_info_;
  }
  _impl_.redirect_info_ = nullptr;
  ::memset(&_impl_.code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.time_remaining_) -
      reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.time_remaining_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Status::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .clarifai.api.status.StatusCode code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_code(static_cast<::clarifai::api::status::StatusCode>(val));
        } else
          goto handle_unusual;
        continue;
      // string description = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_description();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.Status.description"));
        } else
          goto handle_unusual;
        continue;
      // string details = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_details();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.Status.details"));
        } else
          goto handle_unusual;
        continue;
      // repeated string stack_trace = 4 [(.clarifai.auth.util.cl_private_field) = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_stack_trace();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.Status.stack_trace"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 percent_completed = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.percent_completed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 time_remaining = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _impl_.time_remaining_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string req_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_req_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.Status.req_id"));
        } else
          goto handle_unusual;
        continue;
      // string internal_details = 8 [(.clarifai.auth.util.cl_private_field) = true];
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_internal_details();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.Status.internal_details"));
        } else
          goto handle_unusual;
        continue;
      // .clarifai.api.status.RedirectInfo redirect_info = 9 [(.clarifai.auth.util.cl_private_field) = true];
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_redirect_info(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Status::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.status.Status)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .clarifai.api.status.StatusCode code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_code(), target);
  }

  // string description = 2;
  if (!this->_internal_description().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_description().data(), static_cast<int>(this->_internal_description().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.Status.description");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_description(), target);
  }

  // string details = 3;
  if (!this->_internal_details().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_details().data(), static_cast<int>(this->_internal_details().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.Status.details");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_details(), target);
  }

  // repeated string stack_trace = 4 [(.clarifai.auth.util.cl_private_field) = true];
  for (int i = 0, n = this->_internal_stack_trace_size(); i < n; i++) {
    const auto& s = this->_internal_stack_trace(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.Status.stack_trace");
    target = stream->WriteString(4, s, target);
  }

  // uint32 percent_completed = 5;
  if (this->_internal_percent_completed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_percent_completed(), target);
  }

  // uint32 time_remaining = 6;
  if (this->_internal_time_remaining() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(6, this->_internal_time_remaining(), target);
  }

  // string req_id = 7;
  if (!this->_internal_req_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_req_id().data(), static_cast<int>(this->_internal_req_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.Status.req_id");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_req_id(), target);
  }

  // string internal_details = 8 [(.clarifai.auth.util.cl_private_field) = true];
  if (!this->_internal_internal_details().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_internal_details().data(), static_cast<int>(this->_internal_internal_details().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.Status.internal_details");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_internal_details(), target);
  }

  // .clarifai.api.status.RedirectInfo redirect_info = 9 [(.clarifai.auth.util.cl_private_field) = true];
  if (this->_internal_has_redirect_info()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::redirect_info(this),
        _Internal::redirect_info(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.status.Status)
  return target;
}

size_t Status::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.status.Status)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string stack_trace = 4 [(.clarifai.auth.util.cl_private_field) = true];
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.stack_trace_.size());
  for (int i = 0, n = _impl_.stack_trace_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.stack_trace_.Get(i));
  }

  // string description = 2;
  if (!this->_internal_description().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_description());
  }

  // string details = 3;
  if (!this->_internal_details().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_details());
  }

  // string req_id = 7;
  if (!this->_internal_req_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_req_id());
  }

  // string internal_details = 8 [(.clarifai.auth.util.cl_private_field) = true];
  if (!this->_internal_internal_details().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_internal_details());
  }

  // .clarifai.api.status.RedirectInfo redirect_info = 9 [(.clarifai.auth.util.cl_private_field) = true];
  if (this->_internal_has_redirect_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.redirect_info_);
  }

  // .clarifai.api.status.StatusCode code = 1;
  if (this->_internal_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_code());
  }

  // uint32 percent_completed = 5;
  if (this->_internal_percent_completed() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_percent_completed());
  }

  // uint32 time_remaining = 6;
  if (this->_internal_time_remaining() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_time_remaining());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Status::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Status::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Status::GetClassData() const { return &_class_data_; }


void Status::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Status*>(&to_msg);
  auto& from = static_cast<const Status&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.status.Status)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.stack_trace_.MergeFrom(from._impl_.stack_trace_);
  if (!from._internal_description().empty()) {
    _this->_internal_set_description(from._internal_description());
  }
  if (!from._internal_details().empty()) {
    _this->_internal_set_details(from._internal_details());
  }
  if (!from._internal_req_id().empty()) {
    _this->_internal_set_req_id(from._internal_req_id());
  }
  if (!from._internal_internal_details().empty()) {
    _this->_internal_set_internal_details(from._internal_internal_details());
  }
  if (from._internal_has_redirect_info()) {
    _this->_internal_mutable_redirect_info()->::clarifai::api::status::RedirectInfo::MergeFrom(
        from._internal_redirect_info());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  if (from._internal_percent_completed() != 0) {
    _this->_internal_set_percent_completed(from._internal_percent_completed());
  }
  if (from._internal_time_remaining() != 0) {
    _this->_internal_set_time_remaining(from._internal_time_remaining());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Status::CopyFrom(const Status& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.status.Status)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Status::IsInitialized() const {
  return true;
}

void Status::InternalSwap(Status* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.stack_trace_.InternalSwap(&other->_impl_.stack_trace_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.description_, lhs_arena,
      &other->_impl_.description_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.details_, lhs_arena,
      &other->_impl_.details_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.req_id_, lhs_arena,
      &other->_impl_.req_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.internal_details_, lhs_arena,
      &other->_impl_.internal_details_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Status, _impl_.time_remaining_)
      + sizeof(Status::_impl_.time_remaining_)
      - PROTOBUF_FIELD_OFFSET(Status, _impl_.redirect_info_)>(
          reinterpret_cast<char*>(&_impl_.redirect_info_),
          reinterpret_cast<char*>(&other->_impl_.redirect_info_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Status::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto[0]);
}

// ===================================================================

class RedirectInfo::_Internal {
 public:
};

RedirectInfo::RedirectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.status.RedirectInfo)
}
RedirectInfo::RedirectInfo(const RedirectInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RedirectInfo* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.url_){}
    , decltype(_impl_.resource_type_){}
    , decltype(_impl_.old_resource_id_){}
    , decltype(_impl_.new_resource_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_url().empty()) {
    _this->_impl_.url_.Set(from._internal_url(), 
      _this->GetArenaForAllocation());
  }
  _impl_.resource_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_resource_type().empty()) {
    _this->_impl_.resource_type_.Set(from._internal_resource_type(), 
      _this->GetArenaForAllocation());
  }
  _impl_.old_resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.old_resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_old_resource_id().empty()) {
    _this->_impl_.old_resource_id_.Set(from._internal_old_resource_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.new_resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_new_resource_id().empty()) {
    _this->_impl_.new_resource_id_.Set(from._internal_new_resource_id(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.status.RedirectInfo)
}

inline void RedirectInfo::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.url_){}
    , decltype(_impl_.resource_type_){}
    , decltype(_impl_.old_resource_id_){}
    , decltype(_impl_.new_resource_id_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.url_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.url_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.resource_type_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.old_resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.old_resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.new_resource_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.new_resource_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RedirectInfo::~RedirectInfo() {
  // @@protoc_insertion_point(destructor:clarifai.api.status.RedirectInfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RedirectInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.url_.Destroy();
  _impl_.resource_type_.Destroy();
  _impl_.old_resource_id_.Destroy();
  _impl_.new_resource_id_.Destroy();
}

void RedirectInfo::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RedirectInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.status.RedirectInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.url_.ClearToEmpty();
  _impl_.resource_type_.ClearToEmpty();
  _impl_.old_resource_id_.ClearToEmpty();
  _impl_.new_resource_id_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RedirectInfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string url = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_url();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.RedirectInfo.url"));
        } else
          goto handle_unusual;
        continue;
      // string resource_type = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_resource_type();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.RedirectInfo.resource_type"));
        } else
          goto handle_unusual;
        continue;
      // string old_resource_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_old_resource_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.RedirectInfo.old_resource_id"));
        } else
          goto handle_unusual;
        continue;
      // string new_resource_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_new_resource_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.status.RedirectInfo.new_resource_id"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RedirectInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.status.RedirectInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string url = 1;
  if (!this->_internal_url().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_url().data(), static_cast<int>(this->_internal_url().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.RedirectInfo.url");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_url(), target);
  }

  // string resource_type = 2;
  if (!this->_internal_resource_type().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_resource_type().data(), static_cast<int>(this->_internal_resource_type().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.RedirectInfo.resource_type");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_resource_type(), target);
  }

  // string old_resource_id = 3;
  if (!this->_internal_old_resource_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_old_resource_id().data(), static_cast<int>(this->_internal_old_resource_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.RedirectInfo.old_resource_id");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_old_resource_id(), target);
  }

  // string new_resource_id = 4;
  if (!this->_internal_new_resource_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_new_resource_id().data(), static_cast<int>(this->_internal_new_resource_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.status.RedirectInfo.new_resource_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_new_resource_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.status.RedirectInfo)
  return target;
}

size_t RedirectInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.status.RedirectInfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string url = 1;
  if (!this->_internal_url().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_url());
  }

  // string resource_type = 2;
  if (!this->_internal_resource_type().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_resource_type());
  }

  // string old_resource_id = 3;
  if (!this->_internal_old_resource_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_old_resource_id());
  }

  // string new_resource_id = 4;
  if (!this->_internal_new_resource_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_new_resource_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RedirectInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RedirectInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RedirectInfo::GetClassData() const { return &_class_data_; }


void RedirectInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RedirectInfo*>(&to_msg);
  auto& from = static_cast<const RedirectInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.status.RedirectInfo)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_url().empty()) {
    _this->_internal_set_url(from._internal_url());
  }
  if (!from._internal_resource_type().empty()) {
    _this->_internal_set_resource_type(from._internal_resource_type());
  }
  if (!from._internal_old_resource_id().empty()) {
    _this->_internal_set_old_resource_id(from._internal_old_resource_id());
  }
  if (!from._internal_new_resource_id().empty()) {
    _this->_internal_set_new_resource_id(from._internal_new_resource_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RedirectInfo::CopyFrom(const RedirectInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.status.RedirectInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RedirectInfo::IsInitialized() const {
  return true;
}

void RedirectInfo::InternalSwap(RedirectInfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.url_, lhs_arena,
      &other->_impl_.url_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.resource_type_, lhs_arena,
      &other->_impl_.resource_type_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.old_resource_id_, lhs_arena,
      &other->_impl_.old_resource_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.new_resource_id_, lhs_arena,
      &other->_impl_.new_resource_id_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata RedirectInfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto[1]);
}

// ===================================================================

class BaseResponse::_Internal {
 public:
  static const ::clarifai::api::status::Status& status(const BaseResponse* msg);
};

const ::clarifai::api::status::Status&
BaseResponse::_Internal::status(const BaseResponse* msg) {
  return *msg->_impl_.status_;
}
BaseResponse::BaseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.status.BaseResponse)
}
BaseResponse::BaseResponse(const BaseResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  BaseResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_status()) {
    _this->_impl_.status_ = new ::clarifai::api::status::Status(*from._impl_.status_);
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.status.BaseResponse)
}

inline void BaseResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.status_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BaseResponse::~BaseResponse() {
  // @@protoc_insertion_point(destructor:clarifai.api.status.BaseResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BaseResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.status_;
}

void BaseResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BaseResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.status.BaseResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.status_ != nullptr) {
    delete _impl_.status_;
  }
  _impl_.status_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* BaseResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .clarifai.api.status.Status status = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_status(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BaseResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.status.BaseResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .clarifai.api.status.Status status = 1;
  if (this->_internal_has_status()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::status(this),
        _Internal::status(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.status.BaseResponse)
  return target;
}

size_t BaseResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.status.BaseResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .clarifai.api.status.Status status = 1;
  if (this->_internal_has_status()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.status_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData BaseResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    BaseResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*BaseResponse::GetClassData() const { return &_class_data_; }


void BaseResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<BaseResponse*>(&to_msg);
  auto& from = static_cast<const BaseResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.status.BaseResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_status()) {
    _this->_internal_mutable_status()->::clarifai::api::status::Status::MergeFrom(
        from._internal_status());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void BaseResponse::CopyFrom(const BaseResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.status.BaseResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BaseResponse::IsInitialized() const {
  return true;
}

void BaseResponse::InternalSwap(BaseResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.status_, other->_impl_.status_);
}

::PROTOBUF_NAMESPACE_ID::Metadata BaseResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace status
}  // namespace api
}  // namespace clarifai
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::clarifai::api::status::Status*
Arena::CreateMaybeMessage< ::clarifai::api::status::Status >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::status::Status >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::status::RedirectInfo*
Arena::CreateMaybeMessage< ::clarifai::api::status::RedirectInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::status::RedirectInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::status::BaseResponse*
Arena::CreateMaybeMessage< ::clarifai::api::status::BaseResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::status::BaseResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
