// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/status/status.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "proto/clarifai/auth/util/extension.pb.h"
#include "proto/clarifai/api/status/status_code.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto;
namespace clarifai {
namespace api {
namespace status {
class BaseResponse;
struct BaseResponseDefaultTypeInternal;
extern BaseResponseDefaultTypeInternal _BaseResponse_default_instance_;
class RedirectInfo;
struct RedirectInfoDefaultTypeInternal;
extern RedirectInfoDefaultTypeInternal _RedirectInfo_default_instance_;
class Status;
struct StatusDefaultTypeInternal;
extern StatusDefaultTypeInternal _Status_default_instance_;
}  // namespace status
}  // namespace api
}  // namespace clarifai
PROTOBUF_NAMESPACE_OPEN
template<> ::clarifai::api::status::BaseResponse* Arena::CreateMaybeMessage<::clarifai::api::status::BaseResponse>(Arena*);
template<> ::clarifai::api::status::RedirectInfo* Arena::CreateMaybeMessage<::clarifai::api::status::RedirectInfo>(Arena*);
template<> ::clarifai::api::status::Status* Arena::CreateMaybeMessage<::clarifai::api::status::Status>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace clarifai {
namespace api {
namespace status {

// ===================================================================

class Status final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:clarifai.api.status.Status) */ {
 public:
  inline Status() : Status(nullptr) {}
  ~Status() override;
  explicit PROTOBUF_CONSTEXPR Status(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Status(const Status& from);
  Status(Status&& from) noexcept
    : Status() {
    *this = ::std::move(from);
  }

  inline Status& operator=(const Status& from) {
    CopyFrom(from);
    return *this;
  }
  inline Status& operator=(Status&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Status& default_instance() {
    return *internal_default_instance();
  }
  static inline const Status* internal_default_instance() {
    return reinterpret_cast<const Status*>(
               &_Status_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Status& a, Status& b) {
    a.Swap(&b);
  }
  inline void Swap(Status* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Status* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Status* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Status>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Status& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Status& from) {
    Status::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Status* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "clarifai.api.status.Status";
  }
  protected:
  explicit Status(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStackTraceFieldNumber = 4,
    kDescriptionFieldNumber = 2,
    kDetailsFieldNumber = 3,
    kReqIdFieldNumber = 7,
    kInternalDetailsFieldNumber = 8,
    kRedirectInfoFieldNumber = 9,
    kCodeFieldNumber = 1,
    kPercentCompletedFieldNumber = 5,
    kTimeRemainingFieldNumber = 6,
  };
  // repeated string stack_trace = 4 [(.clarifai.auth.util.cl_private_field) = true];
  int stack_trace_size() const;
  private:
  int _internal_stack_trace_size() const;
  public:
  void clear_stack_trace();
  const std::string& stack_trace(int index) const;
  std::string* mutable_stack_trace(int index);
  void set_stack_trace(int index, const std::string& value);
  void set_stack_trace(int index, std::string&& value);
  void set_stack_trace(int index, const char* value);
  void set_stack_trace(int index, const char* value, size_t size);
  std::string* add_stack_trace();
  void add_stack_trace(const std::string& value);
  void add_stack_trace(std::string&& value);
  void add_stack_trace(const char* value);
  void add_stack_trace(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& stack_trace() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_stack_trace();
  private:
  const std::string& _internal_stack_trace(int index) const;
  std::string* _internal_add_stack_trace();
  public:

  // string description = 2;
  void clear_description();
  const std::string& description() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_description(ArgT0&& arg0, ArgT... args);
  std::string* mutable_description();
  PROTOBUF_NODISCARD std::string* release_description();
  void set_allocated_description(std::string* description);
  private:
  const std::string& _internal_description() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_description(const std::string& value);
  std::string* _internal_mutable_description();
  public:

  // string details = 3;
  void clear_details();
  const std::string& details() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_details(ArgT0&& arg0, ArgT... args);
  std::string* mutable_details();
  PROTOBUF_NODISCARD std::string* release_details();
  void set_allocated_details(std::string* details);
  private:
  const std::string& _internal_details() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_details(const std::string& value);
  std::string* _internal_mutable_details();
  public:

  // string req_id = 7;
  void clear_req_id();
  const std::string& req_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_req_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_req_id();
  PROTOBUF_NODISCARD std::string* release_req_id();
  void set_allocated_req_id(std::string* req_id);
  private:
  const std::string& _internal_req_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_req_id(const std::string& value);
  std::string* _internal_mutable_req_id();
  public:

  // string internal_details = 8 [(.clarifai.auth.util.cl_private_field) = true];
  void clear_internal_details();
  const std::string& internal_details() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_internal_details(ArgT0&& arg0, ArgT... args);
  std::string* mutable_internal_details();
  PROTOBUF_NODISCARD std::string* release_internal_details();
  void set_allocated_internal_details(std::string* internal_details);
  private:
  const std::string& _internal_internal_details() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_internal_details(const std::string& value);
  std::string* _internal_mutable_internal_details();
  public:

  // .clarifai.api.status.RedirectInfo redirect_info = 9 [(.clarifai.auth.util.cl_private_field) = true];
  bool has_redirect_info() const;
  private:
  bool _internal_has_redirect_info() const;
  public:
  void clear_redirect_info();
  const ::clarifai::api::status::RedirectInfo& redirect_info() const;
  PROTOBUF_NODISCARD ::clarifai::api::status::RedirectInfo* release_redirect_info();
  ::clarifai::api::status::RedirectInfo* mutable_redirect_info();
  void set_allocated_redirect_info(::clarifai::api::status::RedirectInfo* redirect_info);
  private:
  const ::clarifai::api::status::RedirectInfo& _internal_redirect_info() const;
  ::clarifai::api::status::RedirectInfo* _internal_mutable_redirect_info();
  public:
  void unsafe_arena_set_allocated_redirect_info(
      ::clarifai::api::status::RedirectInfo* redirect_info);
  ::clarifai::api::status::RedirectInfo* unsafe_arena_release_redirect_info();

  // .clarifai.api.status.StatusCode code = 1;
  void clear_code();
  ::clarifai::api::status::StatusCode code() const;
  void set_code(::clarifai::api::status::StatusCode value);
  private:
  ::clarifai::api::status::StatusCode _internal_code() const;
  void _internal_set_code(::clarifai::api::status::StatusCode value);
  public:

  // uint32 percent_completed = 5;
  void clear_percent_completed();
  uint32_t percent_completed() const;
  void set_percent_completed(uint32_t value);
  private:
  uint32_t _internal_percent_completed() const;
  void _internal_set_percent_completed(uint32_t value);
  public:

  // uint32 time_remaining = 6;
  void clear_time_remaining();
  uint32_t time_remaining() const;
  void set_time_remaining(uint32_t value);
  private:
  uint32_t _internal_time_remaining() const;
  void _internal_set_time_remaining(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:clarifai.api.status.Status)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> stack_trace_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr description_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr details_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr req_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr internal_details_;
    ::clarifai::api::status::RedirectInfo* redirect_info_;
    int code_;
    uint32_t percent_completed_;
    uint32_t time_remaining_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto;
};
// -------------------------------------------------------------------

class RedirectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:clarifai.api.status.RedirectInfo) */ {
 public:
  inline RedirectInfo() : RedirectInfo(nullptr) {}
  ~RedirectInfo() override;
  explicit PROTOBUF_CONSTEXPR RedirectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RedirectInfo(const RedirectInfo& from);
  RedirectInfo(RedirectInfo&& from) noexcept
    : RedirectInfo() {
    *this = ::std::move(from);
  }

  inline RedirectInfo& operator=(const RedirectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RedirectInfo& operator=(RedirectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RedirectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const RedirectInfo* internal_default_instance() {
    return reinterpret_cast<const RedirectInfo*>(
               &_RedirectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RedirectInfo& a, RedirectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(RedirectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RedirectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RedirectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RedirectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RedirectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const RedirectInfo& from) {
    RedirectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RedirectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "clarifai.api.status.RedirectInfo";
  }
  protected:
  explicit RedirectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUrlFieldNumber = 1,
    kResourceTypeFieldNumber = 2,
    kOldResourceIdFieldNumber = 3,
    kNewResourceIdFieldNumber = 4,
  };
  // string url = 1;
  void clear_url();
  const std::string& url() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_url(ArgT0&& arg0, ArgT... args);
  std::string* mutable_url();
  PROTOBUF_NODISCARD std::string* release_url();
  void set_allocated_url(std::string* url);
  private:
  const std::string& _internal_url() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_url(const std::string& value);
  std::string* _internal_mutable_url();
  public:

  // string resource_type = 2;
  void clear_resource_type();
  const std::string& resource_type() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_resource_type(ArgT0&& arg0, ArgT... args);
  std::string* mutable_resource_type();
  PROTOBUF_NODISCARD std::string* release_resource_type();
  void set_allocated_resource_type(std::string* resource_type);
  private:
  const std::string& _internal_resource_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_resource_type(const std::string& value);
  std::string* _internal_mutable_resource_type();
  public:

  // string old_resource_id = 3;
  void clear_old_resource_id();
  const std::string& old_resource_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_old_resource_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_old_resource_id();
  PROTOBUF_NODISCARD std::string* release_old_resource_id();
  void set_allocated_old_resource_id(std::string* old_resource_id);
  private:
  const std::string& _internal_old_resource_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_old_resource_id(const std::string& value);
  std::string* _internal_mutable_old_resource_id();
  public:

  // string new_resource_id = 4;
  void clear_new_resource_id();
  const std::string& new_resource_id() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_new_resource_id(ArgT0&& arg0, ArgT... args);
  std::string* mutable_new_resource_id();
  PROTOBUF_NODISCARD std::string* release_new_resource_id();
  void set_allocated_new_resource_id(std::string* new_resource_id);
  private:
  const std::string& _internal_new_resource_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_new_resource_id(const std::string& value);
  std::string* _internal_mutable_new_resource_id();
  public:

  // @@protoc_insertion_point(class_scope:clarifai.api.status.RedirectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr url_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr resource_type_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr old_resource_id_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr new_resource_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto;
};
// -------------------------------------------------------------------

class BaseResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:clarifai.api.status.BaseResponse) */ {
 public:
  inline BaseResponse() : BaseResponse(nullptr) {}
  ~BaseResponse() override;
  explicit PROTOBUF_CONSTEXPR BaseResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BaseResponse(const BaseResponse& from);
  BaseResponse(BaseResponse&& from) noexcept
    : BaseResponse() {
    *this = ::std::move(from);
  }

  inline BaseResponse& operator=(const BaseResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseResponse& operator=(BaseResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const BaseResponse* internal_default_instance() {
    return reinterpret_cast<const BaseResponse*>(
               &_BaseResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(BaseResponse& a, BaseResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(BaseResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BaseResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BaseResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BaseResponse& from) {
    BaseResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BaseResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "clarifai.api.status.BaseResponse";
  }
  protected:
  explicit BaseResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // .clarifai.api.status.Status status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const ::clarifai::api::status::Status& status() const;
  PROTOBUF_NODISCARD ::clarifai::api::status::Status* release_status();
  ::clarifai::api::status::Status* mutable_status();
  void set_allocated_status(::clarifai::api::status::Status* status);
  private:
  const ::clarifai::api::status::Status& _internal_status() const;
  ::clarifai::api::status::Status* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::clarifai::api::status::Status* status);
  ::clarifai::api::status::Status* unsafe_arena_release_status();

  // @@protoc_insertion_point(class_scope:clarifai.api.status.BaseResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::clarifai::api::status::Status* status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Status

// .clarifai.api.status.StatusCode code = 1;
inline void Status::clear_code() {
  _impl_.code_ = 0;
}
inline ::clarifai::api::status::StatusCode Status::_internal_code() const {
  return static_cast< ::clarifai::api::status::StatusCode >(_impl_.code_);
}
inline ::clarifai::api::status::StatusCode Status::code() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.code)
  return _internal_code();
}
inline void Status::_internal_set_code(::clarifai::api::status::StatusCode value) {
  
  _impl_.code_ = value;
}
inline void Status::set_code(::clarifai::api::status::StatusCode value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.code)
}

// string description = 2;
inline void Status::clear_description() {
  _impl_.description_.ClearToEmpty();
}
inline const std::string& Status::description() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.description)
  return _internal_description();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Status::set_description(ArgT0&& arg0, ArgT... args) {
 
 _impl_.description_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.description)
}
inline std::string* Status::mutable_description() {
  std::string* _s = _internal_mutable_description();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.description)
  return _s;
}
inline const std::string& Status::_internal_description() const {
  return _impl_.description_.Get();
}
inline void Status::_internal_set_description(const std::string& value) {
  
  _impl_.description_.Set(value, GetArenaForAllocation());
}
inline std::string* Status::_internal_mutable_description() {
  
  return _impl_.description_.Mutable(GetArenaForAllocation());
}
inline std::string* Status::release_description() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.Status.description)
  return _impl_.description_.Release();
}
inline void Status::set_allocated_description(std::string* description) {
  if (description != nullptr) {
    
  } else {
    
  }
  _impl_.description_.SetAllocated(description, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.description_.IsDefault()) {
    _impl_.description_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.Status.description)
}

// string details = 3;
inline void Status::clear_details() {
  _impl_.details_.ClearToEmpty();
}
inline const std::string& Status::details() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.details)
  return _internal_details();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Status::set_details(ArgT0&& arg0, ArgT... args) {
 
 _impl_.details_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.details)
}
inline std::string* Status::mutable_details() {
  std::string* _s = _internal_mutable_details();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.details)
  return _s;
}
inline const std::string& Status::_internal_details() const {
  return _impl_.details_.Get();
}
inline void Status::_internal_set_details(const std::string& value) {
  
  _impl_.details_.Set(value, GetArenaForAllocation());
}
inline std::string* Status::_internal_mutable_details() {
  
  return _impl_.details_.Mutable(GetArenaForAllocation());
}
inline std::string* Status::release_details() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.Status.details)
  return _impl_.details_.Release();
}
inline void Status::set_allocated_details(std::string* details) {
  if (details != nullptr) {
    
  } else {
    
  }
  _impl_.details_.SetAllocated(details, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.details_.IsDefault()) {
    _impl_.details_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.Status.details)
}

// repeated string stack_trace = 4 [(.clarifai.auth.util.cl_private_field) = true];
inline int Status::_internal_stack_trace_size() const {
  return _impl_.stack_trace_.size();
}
inline int Status::stack_trace_size() const {
  return _internal_stack_trace_size();
}
inline void Status::clear_stack_trace() {
  _impl_.stack_trace_.Clear();
}
inline std::string* Status::add_stack_trace() {
  std::string* _s = _internal_add_stack_trace();
  // @@protoc_insertion_point(field_add_mutable:clarifai.api.status.Status.stack_trace)
  return _s;
}
inline const std::string& Status::_internal_stack_trace(int index) const {
  return _impl_.stack_trace_.Get(index);
}
inline const std::string& Status::stack_trace(int index) const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.stack_trace)
  return _internal_stack_trace(index);
}
inline std::string* Status::mutable_stack_trace(int index) {
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.stack_trace)
  return _impl_.stack_trace_.Mutable(index);
}
inline void Status::set_stack_trace(int index, const std::string& value) {
  _impl_.stack_trace_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.stack_trace)
}
inline void Status::set_stack_trace(int index, std::string&& value) {
  _impl_.stack_trace_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.stack_trace)
}
inline void Status::set_stack_trace(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.stack_trace_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:clarifai.api.status.Status.stack_trace)
}
inline void Status::set_stack_trace(int index, const char* value, size_t size) {
  _impl_.stack_trace_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:clarifai.api.status.Status.stack_trace)
}
inline std::string* Status::_internal_add_stack_trace() {
  return _impl_.stack_trace_.Add();
}
inline void Status::add_stack_trace(const std::string& value) {
  _impl_.stack_trace_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:clarifai.api.status.Status.stack_trace)
}
inline void Status::add_stack_trace(std::string&& value) {
  _impl_.stack_trace_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:clarifai.api.status.Status.stack_trace)
}
inline void Status::add_stack_trace(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.stack_trace_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:clarifai.api.status.Status.stack_trace)
}
inline void Status::add_stack_trace(const char* value, size_t size) {
  _impl_.stack_trace_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:clarifai.api.status.Status.stack_trace)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Status::stack_trace() const {
  // @@protoc_insertion_point(field_list:clarifai.api.status.Status.stack_trace)
  return _impl_.stack_trace_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Status::mutable_stack_trace() {
  // @@protoc_insertion_point(field_mutable_list:clarifai.api.status.Status.stack_trace)
  return &_impl_.stack_trace_;
}

// uint32 percent_completed = 5;
inline void Status::clear_percent_completed() {
  _impl_.percent_completed_ = 0u;
}
inline uint32_t Status::_internal_percent_completed() const {
  return _impl_.percent_completed_;
}
inline uint32_t Status::percent_completed() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.percent_completed)
  return _internal_percent_completed();
}
inline void Status::_internal_set_percent_completed(uint32_t value) {
  
  _impl_.percent_completed_ = value;
}
inline void Status::set_percent_completed(uint32_t value) {
  _internal_set_percent_completed(value);
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.percent_completed)
}

// uint32 time_remaining = 6;
inline void Status::clear_time_remaining() {
  _impl_.time_remaining_ = 0u;
}
inline uint32_t Status::_internal_time_remaining() const {
  return _impl_.time_remaining_;
}
inline uint32_t Status::time_remaining() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.time_remaining)
  return _internal_time_remaining();
}
inline void Status::_internal_set_time_remaining(uint32_t value) {
  
  _impl_.time_remaining_ = value;
}
inline void Status::set_time_remaining(uint32_t value) {
  _internal_set_time_remaining(value);
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.time_remaining)
}

// string req_id = 7;
inline void Status::clear_req_id() {
  _impl_.req_id_.ClearToEmpty();
}
inline const std::string& Status::req_id() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.req_id)
  return _internal_req_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Status::set_req_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.req_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.req_id)
}
inline std::string* Status::mutable_req_id() {
  std::string* _s = _internal_mutable_req_id();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.req_id)
  return _s;
}
inline const std::string& Status::_internal_req_id() const {
  return _impl_.req_id_.Get();
}
inline void Status::_internal_set_req_id(const std::string& value) {
  
  _impl_.req_id_.Set(value, GetArenaForAllocation());
}
inline std::string* Status::_internal_mutable_req_id() {
  
  return _impl_.req_id_.Mutable(GetArenaForAllocation());
}
inline std::string* Status::release_req_id() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.Status.req_id)
  return _impl_.req_id_.Release();
}
inline void Status::set_allocated_req_id(std::string* req_id) {
  if (req_id != nullptr) {
    
  } else {
    
  }
  _impl_.req_id_.SetAllocated(req_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.req_id_.IsDefault()) {
    _impl_.req_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.Status.req_id)
}

// string internal_details = 8 [(.clarifai.auth.util.cl_private_field) = true];
inline void Status::clear_internal_details() {
  _impl_.internal_details_.ClearToEmpty();
}
inline const std::string& Status::internal_details() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.internal_details)
  return _internal_internal_details();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Status::set_internal_details(ArgT0&& arg0, ArgT... args) {
 
 _impl_.internal_details_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.Status.internal_details)
}
inline std::string* Status::mutable_internal_details() {
  std::string* _s = _internal_mutable_internal_details();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.internal_details)
  return _s;
}
inline const std::string& Status::_internal_internal_details() const {
  return _impl_.internal_details_.Get();
}
inline void Status::_internal_set_internal_details(const std::string& value) {
  
  _impl_.internal_details_.Set(value, GetArenaForAllocation());
}
inline std::string* Status::_internal_mutable_internal_details() {
  
  return _impl_.internal_details_.Mutable(GetArenaForAllocation());
}
inline std::string* Status::release_internal_details() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.Status.internal_details)
  return _impl_.internal_details_.Release();
}
inline void Status::set_allocated_internal_details(std::string* internal_details) {
  if (internal_details != nullptr) {
    
  } else {
    
  }
  _impl_.internal_details_.SetAllocated(internal_details, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.internal_details_.IsDefault()) {
    _impl_.internal_details_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.Status.internal_details)
}

// .clarifai.api.status.RedirectInfo redirect_info = 9 [(.clarifai.auth.util.cl_private_field) = true];
inline bool Status::_internal_has_redirect_info() const {
  return this != internal_default_instance() && _impl_.redirect_info_ != nullptr;
}
inline bool Status::has_redirect_info() const {
  return _internal_has_redirect_info();
}
inline void Status::clear_redirect_info() {
  if (GetArenaForAllocation() == nullptr && _impl_.redirect_info_ != nullptr) {
    delete _impl_.redirect_info_;
  }
  _impl_.redirect_info_ = nullptr;
}
inline const ::clarifai::api::status::RedirectInfo& Status::_internal_redirect_info() const {
  const ::clarifai::api::status::RedirectInfo* p = _impl_.redirect_info_;
  return p != nullptr ? *p : reinterpret_cast<const ::clarifai::api::status::RedirectInfo&>(
      ::clarifai::api::status::_RedirectInfo_default_instance_);
}
inline const ::clarifai::api::status::RedirectInfo& Status::redirect_info() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.Status.redirect_info)
  return _internal_redirect_info();
}
inline void Status::unsafe_arena_set_allocated_redirect_info(
    ::clarifai::api::status::RedirectInfo* redirect_info) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.redirect_info_);
  }
  _impl_.redirect_info_ = redirect_info;
  if (redirect_info) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:clarifai.api.status.Status.redirect_info)
}
inline ::clarifai::api::status::RedirectInfo* Status::release_redirect_info() {
  
  ::clarifai::api::status::RedirectInfo* temp = _impl_.redirect_info_;
  _impl_.redirect_info_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::clarifai::api::status::RedirectInfo* Status::unsafe_arena_release_redirect_info() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.Status.redirect_info)
  
  ::clarifai::api::status::RedirectInfo* temp = _impl_.redirect_info_;
  _impl_.redirect_info_ = nullptr;
  return temp;
}
inline ::clarifai::api::status::RedirectInfo* Status::_internal_mutable_redirect_info() {
  
  if (_impl_.redirect_info_ == nullptr) {
    auto* p = CreateMaybeMessage<::clarifai::api::status::RedirectInfo>(GetArenaForAllocation());
    _impl_.redirect_info_ = p;
  }
  return _impl_.redirect_info_;
}
inline ::clarifai::api::status::RedirectInfo* Status::mutable_redirect_info() {
  ::clarifai::api::status::RedirectInfo* _msg = _internal_mutable_redirect_info();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.Status.redirect_info)
  return _msg;
}
inline void Status::set_allocated_redirect_info(::clarifai::api::status::RedirectInfo* redirect_info) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.redirect_info_;
  }
  if (redirect_info) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(redirect_info);
    if (message_arena != submessage_arena) {
      redirect_info = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, redirect_info, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.redirect_info_ = redirect_info;
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.Status.redirect_info)
}

// -------------------------------------------------------------------

// RedirectInfo

// string url = 1;
inline void RedirectInfo::clear_url() {
  _impl_.url_.ClearToEmpty();
}
inline const std::string& RedirectInfo::url() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.RedirectInfo.url)
  return _internal_url();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RedirectInfo::set_url(ArgT0&& arg0, ArgT... args) {
 
 _impl_.url_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.RedirectInfo.url)
}
inline std::string* RedirectInfo::mutable_url() {
  std::string* _s = _internal_mutable_url();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.RedirectInfo.url)
  return _s;
}
inline const std::string& RedirectInfo::_internal_url() const {
  return _impl_.url_.Get();
}
inline void RedirectInfo::_internal_set_url(const std::string& value) {
  
  _impl_.url_.Set(value, GetArenaForAllocation());
}
inline std::string* RedirectInfo::_internal_mutable_url() {
  
  return _impl_.url_.Mutable(GetArenaForAllocation());
}
inline std::string* RedirectInfo::release_url() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.RedirectInfo.url)
  return _impl_.url_.Release();
}
inline void RedirectInfo::set_allocated_url(std::string* url) {
  if (url != nullptr) {
    
  } else {
    
  }
  _impl_.url_.SetAllocated(url, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.url_.IsDefault()) {
    _impl_.url_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.RedirectInfo.url)
}

// string resource_type = 2;
inline void RedirectInfo::clear_resource_type() {
  _impl_.resource_type_.ClearToEmpty();
}
inline const std::string& RedirectInfo::resource_type() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.RedirectInfo.resource_type)
  return _internal_resource_type();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RedirectInfo::set_resource_type(ArgT0&& arg0, ArgT... args) {
 
 _impl_.resource_type_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.RedirectInfo.resource_type)
}
inline std::string* RedirectInfo::mutable_resource_type() {
  std::string* _s = _internal_mutable_resource_type();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.RedirectInfo.resource_type)
  return _s;
}
inline const std::string& RedirectInfo::_internal_resource_type() const {
  return _impl_.resource_type_.Get();
}
inline void RedirectInfo::_internal_set_resource_type(const std::string& value) {
  
  _impl_.resource_type_.Set(value, GetArenaForAllocation());
}
inline std::string* RedirectInfo::_internal_mutable_resource_type() {
  
  return _impl_.resource_type_.Mutable(GetArenaForAllocation());
}
inline std::string* RedirectInfo::release_resource_type() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.RedirectInfo.resource_type)
  return _impl_.resource_type_.Release();
}
inline void RedirectInfo::set_allocated_resource_type(std::string* resource_type) {
  if (resource_type != nullptr) {
    
  } else {
    
  }
  _impl_.resource_type_.SetAllocated(resource_type, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.resource_type_.IsDefault()) {
    _impl_.resource_type_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.RedirectInfo.resource_type)
}

// string old_resource_id = 3;
inline void RedirectInfo::clear_old_resource_id() {
  _impl_.old_resource_id_.ClearToEmpty();
}
inline const std::string& RedirectInfo::old_resource_id() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.RedirectInfo.old_resource_id)
  return _internal_old_resource_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RedirectInfo::set_old_resource_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.old_resource_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.RedirectInfo.old_resource_id)
}
inline std::string* RedirectInfo::mutable_old_resource_id() {
  std::string* _s = _internal_mutable_old_resource_id();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.RedirectInfo.old_resource_id)
  return _s;
}
inline const std::string& RedirectInfo::_internal_old_resource_id() const {
  return _impl_.old_resource_id_.Get();
}
inline void RedirectInfo::_internal_set_old_resource_id(const std::string& value) {
  
  _impl_.old_resource_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RedirectInfo::_internal_mutable_old_resource_id() {
  
  return _impl_.old_resource_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RedirectInfo::release_old_resource_id() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.RedirectInfo.old_resource_id)
  return _impl_.old_resource_id_.Release();
}
inline void RedirectInfo::set_allocated_old_resource_id(std::string* old_resource_id) {
  if (old_resource_id != nullptr) {
    
  } else {
    
  }
  _impl_.old_resource_id_.SetAllocated(old_resource_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.old_resource_id_.IsDefault()) {
    _impl_.old_resource_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.RedirectInfo.old_resource_id)
}

// string new_resource_id = 4;
inline void RedirectInfo::clear_new_resource_id() {
  _impl_.new_resource_id_.ClearToEmpty();
}
inline const std::string& RedirectInfo::new_resource_id() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.RedirectInfo.new_resource_id)
  return _internal_new_resource_id();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void RedirectInfo::set_new_resource_id(ArgT0&& arg0, ArgT... args) {
 
 _impl_.new_resource_id_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:clarifai.api.status.RedirectInfo.new_resource_id)
}
inline std::string* RedirectInfo::mutable_new_resource_id() {
  std::string* _s = _internal_mutable_new_resource_id();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.RedirectInfo.new_resource_id)
  return _s;
}
inline const std::string& RedirectInfo::_internal_new_resource_id() const {
  return _impl_.new_resource_id_.Get();
}
inline void RedirectInfo::_internal_set_new_resource_id(const std::string& value) {
  
  _impl_.new_resource_id_.Set(value, GetArenaForAllocation());
}
inline std::string* RedirectInfo::_internal_mutable_new_resource_id() {
  
  return _impl_.new_resource_id_.Mutable(GetArenaForAllocation());
}
inline std::string* RedirectInfo::release_new_resource_id() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.RedirectInfo.new_resource_id)
  return _impl_.new_resource_id_.Release();
}
inline void RedirectInfo::set_allocated_new_resource_id(std::string* new_resource_id) {
  if (new_resource_id != nullptr) {
    
  } else {
    
  }
  _impl_.new_resource_id_.SetAllocated(new_resource_id, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.new_resource_id_.IsDefault()) {
    _impl_.new_resource_id_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.RedirectInfo.new_resource_id)
}

// -------------------------------------------------------------------

// BaseResponse

// .clarifai.api.status.Status status = 1;
inline bool BaseResponse::_internal_has_status() const {
  return this != internal_default_instance() && _impl_.status_ != nullptr;
}
inline bool BaseResponse::has_status() const {
  return _internal_has_status();
}
inline void BaseResponse::clear_status() {
  if (GetArenaForAllocation() == nullptr && _impl_.status_ != nullptr) {
    delete _impl_.status_;
  }
  _impl_.status_ = nullptr;
}
inline const ::clarifai::api::status::Status& BaseResponse::_internal_status() const {
  const ::clarifai::api::status::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::clarifai::api::status::Status&>(
      ::clarifai::api::status::_Status_default_instance_);
}
inline const ::clarifai::api::status::Status& BaseResponse::status() const {
  // @@protoc_insertion_point(field_get:clarifai.api.status.BaseResponse.status)
  return _internal_status();
}
inline void BaseResponse::unsafe_arena_set_allocated_status(
    ::clarifai::api::status::Status* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:clarifai.api.status.BaseResponse.status)
}
inline ::clarifai::api::status::Status* BaseResponse::release_status() {
  
  ::clarifai::api::status::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::clarifai::api::status::Status* BaseResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:clarifai.api.status.BaseResponse.status)
  
  ::clarifai::api::status::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::clarifai::api::status::Status* BaseResponse::_internal_mutable_status() {
  
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::clarifai::api::status::Status>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::clarifai::api::status::Status* BaseResponse::mutable_status() {
  ::clarifai::api::status::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:clarifai.api.status.BaseResponse.status)
  return _msg;
}
inline void BaseResponse::set_allocated_status(::clarifai::api::status::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.status_;
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(status);
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.status.BaseResponse.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace status
}  // namespace api
}  // namespace clarifai

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fclarifai_2fapi_2fstatus_2fstatus_2eproto
