// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/utils/matrix.proto

#include "proto/clarifai/api/utils/matrix.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR MatrixUint64::MatrixUint64(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.data_)*/{}
  , /*decltype(_impl_._data_cached_byte_size_)*/{0}
  , /*decltype(_impl_.n_cols_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct MatrixUint64DefaultTypeInternal {
  PROTOBUF_CONSTEXPR MatrixUint64DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~MatrixUint64DefaultTypeInternal() {}
  union {
    MatrixUint64 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MatrixUint64DefaultTypeInternal _MatrixUint64_default_instance_;
static ::_pb::Metadata file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = nullptr;

const uint32_t TableStruct_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, _impl_.n_cols_),
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, _impl_.data_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MatrixUint64)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_MatrixUint64_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n%proto/clarifai/api/utils/matrix.proto\""
  ",\n\014MatrixUint64\022\016\n\006n_cols\030\001 \001(\004\022\014\n\004data\030"
  "\002 \003(\004B\\\n\033com.clarifai.grpc.api.utilsZ=gi"
  "thub.com/Clarifai/clarifai-go-grpc/proto"
  "/clarifai/api/utilsb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = {
    false, false, 187, descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto,
    "proto/clarifai/api/utils/matrix.proto",
    &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto::offsets,
    file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto, file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto,
    file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_getter() {
  return &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto(&descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto);

// ===================================================================

class MatrixUint64::_Internal {
 public:
};

MatrixUint64::MatrixUint64(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:MatrixUint64)
}
MatrixUint64::MatrixUint64(const MatrixUint64& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  MatrixUint64* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){from._impl_.data_}
    , /*decltype(_impl_._data_cached_byte_size_)*/{0}
    , decltype(_impl_.n_cols_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.n_cols_ = from._impl_.n_cols_;
  // @@protoc_insertion_point(copy_constructor:MatrixUint64)
}

inline void MatrixUint64::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.data_){arena}
    , /*decltype(_impl_._data_cached_byte_size_)*/{0}
    , decltype(_impl_.n_cols_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

MatrixUint64::~MatrixUint64() {
  // @@protoc_insertion_point(destructor:MatrixUint64)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void MatrixUint64::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.data_.~RepeatedField();
}

void MatrixUint64::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void MatrixUint64::Clear() {
// @@protoc_insertion_point(message_clear_start:MatrixUint64)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _impl_.n_cols_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MatrixUint64::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 n_cols = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.n_cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint64 data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MatrixUint64::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MatrixUint64)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_n_cols(), target);
  }

  // repeated uint64 data = 2;
  {
    int byte_size = _impl_._data_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          2, _internal_data(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MatrixUint64)
  return target;
}

size_t MatrixUint64::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MatrixUint64)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 data = 2;
  {
    size_t data_size = ::_pbi::WireFormatLite::
      UInt64Size(this->_impl_.data_);
    if (data_size > 0) {
      total_size += 1 +
        ::_pbi::WireFormatLite::Int32Size(static_cast<int32_t>(data_size));
    }
    int cached_size = ::_pbi::ToCachedSize(data_size);
    _impl_._data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint64 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_n_cols());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatrixUint64::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    MatrixUint64::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatrixUint64::GetClassData() const { return &_class_data_; }


void MatrixUint64::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<MatrixUint64*>(&to_msg);
  auto& from = static_cast<const MatrixUint64&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MatrixUint64)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_n_cols() != 0) {
    _this->_internal_set_n_cols(from._internal_n_cols());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MatrixUint64::CopyFrom(const MatrixUint64& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MatrixUint64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatrixUint64::IsInitialized() const {
  return true;
}

void MatrixUint64::InternalSwap(MatrixUint64* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
  swap(_impl_.n_cols_, other->_impl_.n_cols_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MatrixUint64::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MatrixUint64*
Arena::CreateMaybeMessage< ::MatrixUint64 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MatrixUint64 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
