// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/utils/matrix.proto

#include "proto/clarifai/api/utils/matrix.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr MatrixUint64::MatrixUint64(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : data_()
  , _data_cached_byte_size_(0)
  , n_cols_(uint64_t{0u}){}
struct MatrixUint64DefaultTypeInternal {
  constexpr MatrixUint64DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~MatrixUint64DefaultTypeInternal() {}
  union {
    MatrixUint64 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT MatrixUint64DefaultTypeInternal _MatrixUint64_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = nullptr;

const uint32_t TableStruct_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, n_cols_),
  PROTOBUF_FIELD_OFFSET(::MatrixUint64, data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::MatrixUint64)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_MatrixUint64_default_instance_),
};

const char descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n%proto/clarifai/api/utils/matrix.proto\""
  ",\n\014MatrixUint64\022\016\n\006n_cols\030\001 \001(\004\022\014\n\004data\030"
  "\002 \003(\004B\033\n\005utilsZ\022clarifai/api/utilsb\006prot"
  "o3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto = {
  false, false, 122, descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto, "proto/clarifai/api/utils/matrix.proto", 
  &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto::offsets,
  file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto, file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto, file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_getter() {
  return &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto(&descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto);

// ===================================================================

class MatrixUint64::_Internal {
 public:
};

MatrixUint64::MatrixUint64(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  data_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:MatrixUint64)
}
MatrixUint64::MatrixUint64(const MatrixUint64& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      data_(from.data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  n_cols_ = from.n_cols_;
  // @@protoc_insertion_point(copy_constructor:MatrixUint64)
}

inline void MatrixUint64::SharedCtor() {
n_cols_ = uint64_t{0u};
}

MatrixUint64::~MatrixUint64() {
  // @@protoc_insertion_point(destructor:MatrixUint64)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void MatrixUint64::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void MatrixUint64::ArenaDtor(void* object) {
  MatrixUint64* _this = reinterpret_cast< MatrixUint64* >(object);
  (void)_this;
}
void MatrixUint64::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MatrixUint64::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void MatrixUint64::Clear() {
// @@protoc_insertion_point(message_clear_start:MatrixUint64)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  n_cols_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MatrixUint64::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 n_cols = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          n_cols_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated uint64 data = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt64Parser(_internal_mutable_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<uint8_t>(tag) == 16) {
          _internal_add_data(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* MatrixUint64::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MatrixUint64)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_n_cols(), target);
  }

  // repeated uint64 data = 2;
  {
    int byte_size = _data_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt64Packed(
          2, _internal_data(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MatrixUint64)
  return target;
}

size_t MatrixUint64::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MatrixUint64)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint64 data = 2;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt64Size(this->data_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<int32_t>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // uint64 n_cols = 1;
  if (this->_internal_n_cols() != 0) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64SizePlusOne(this->_internal_n_cols());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData MatrixUint64::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    MatrixUint64::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*MatrixUint64::GetClassData() const { return &_class_data_; }

void MatrixUint64::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<MatrixUint64 *>(to)->MergeFrom(
      static_cast<const MatrixUint64 &>(from));
}


void MatrixUint64::MergeFrom(const MatrixUint64& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MatrixUint64)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from._internal_n_cols() != 0) {
    _internal_set_n_cols(from._internal_n_cols());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void MatrixUint64::CopyFrom(const MatrixUint64& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MatrixUint64)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MatrixUint64::IsInitialized() const {
  return true;
}

void MatrixUint64::InternalSwap(MatrixUint64* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  data_.InternalSwap(&other->data_);
  swap(n_cols_, other->n_cols_);
}

::PROTOBUF_NAMESPACE_ID::Metadata MatrixUint64::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2futils_2fmatrix_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MatrixUint64* Arena::CreateMaybeMessage< ::MatrixUint64 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MatrixUint64 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
