// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/clarifai/api/utils/test_proto.proto

#include "proto/clarifai/api/utils/test_proto.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace clarifai {
namespace api {
namespace utils {
PROTOBUF_CONSTEXPR TestProto::TestProto(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.image_bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_.one_of_field_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct TestProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestProtoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestProtoDefaultTypeInternal() {}
  union {
    TestProto _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestProtoDefaultTypeInternal _TestProto_default_instance_;
PROTOBUF_CONSTEXPR TestProto2::TestProto2(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.flip_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TestProto2DefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestProto2DefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestProto2DefaultTypeInternal() {}
  union {
    TestProto2 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestProto2DefaultTypeInternal _TestProto2_default_instance_;
}  // namespace utils
}  // namespace api
}  // namespace clarifai
static ::_pb::Metadata file_level_metadata_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto = nullptr;

const uint32_t TableStruct_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_.image_bytes_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto, _impl_.one_of_field_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto2, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto2, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::clarifai::api::utils::TestProto2, _impl_.flip_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::clarifai::api::utils::TestProto)},
  { 14, -1, -1, sizeof(::clarifai::api::utils::TestProto2)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::clarifai::api::utils::_TestProto_default_instance_._instance,
  &::clarifai::api::utils::_TestProto2_default_instance_._instance,
};

const char descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n)proto/clarifai/api/utils/test_proto.pr"
  "oto\022\022clarifai.api.utils\032)proto/clarifai/"
  "api/utils/extensions.proto\"\345\001\n\tTestProto"
  "\022\n\n\002id\030\001 \001(\t\022(\n\007message\030\002 \001(\tB\027\200\265\030\001\212\265\030\017p"
  "rotos are cool\022\026\n\005value\030\003 \001(\001B\007\325\265\030\000\000\200\?\022\023"
  "\n\013image_bytes\030\004 \001(\014\022\026\n\014string_oneof\030\005 \001("
  "\tH\000\022\024\n\nbool_oneof\030\006 \001(\010H\000\0227\n\rmessage_one"
  "of\030\007 \001(\0132\036.clarifai.api.utils.TestProto2"
  "H\000B\016\n\014one_of_field\"&\n\nTestProto2\022\n\n\002id\030\001"
  " \001(\t\022\014\n\004flip\030\002 \001(\010Be\n\033com.clarifai.grpc."
  "api.utilsP\001Z=github.com/Clarifai/clarifa"
  "i-go-grpc/proto/clarifai/api/utils\242\002\004CAI"
  "Pb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_deps[1] = {
  &::descriptor_table_proto_2fclarifai_2fapi_2futils_2fextensions_2eproto,
};
static ::_pbi::once_flag descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto = {
    false, false, 489, descriptor_table_protodef_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto,
    "proto/clarifai/api/utils/test_proto.proto",
    &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_once, descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto::offsets,
    file_level_metadata_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto, file_level_enum_descriptors_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto,
    file_level_service_descriptors_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_getter() {
  return &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto(&descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto);
namespace clarifai {
namespace api {
namespace utils {

// ===================================================================

class TestProto::_Internal {
 public:
  static const ::clarifai::api::utils::TestProto2& message_oneof(const TestProto* msg);
};

const ::clarifai::api::utils::TestProto2&
TestProto::_Internal::message_oneof(const TestProto* msg) {
  return *msg->_impl_.one_of_field_.message_oneof_;
}
void TestProto::set_allocated_message_oneof(::clarifai::api::utils::TestProto2* message_oneof) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_one_of_field();
  if (message_oneof) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(message_oneof);
    if (message_arena != submessage_arena) {
      message_oneof = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, message_oneof, submessage_arena);
    }
    set_has_message_oneof();
    _impl_.one_of_field_.message_oneof_ = message_oneof;
  }
  // @@protoc_insertion_point(field_set_allocated:clarifai.api.utils.TestProto.message_oneof)
}
TestProto::TestProto(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.utils.TestProto)
}
TestProto::TestProto(const TestProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TestProto* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.image_bytes_){}
    , decltype(_impl_.value_){}
    , decltype(_impl_.one_of_field_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.image_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.image_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_image_bytes().empty()) {
    _this->_impl_.image_bytes_.Set(from._internal_image_bytes(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.value_ = from._impl_.value_;
  clear_has_one_of_field();
  switch (from.one_of_field_case()) {
    case kStringOneof: {
      _this->_internal_set_string_oneof(from._internal_string_oneof());
      break;
    }
    case kBoolOneof: {
      _this->_internal_set_bool_oneof(from._internal_bool_oneof());
      break;
    }
    case kMessageOneof: {
      _this->_internal_mutable_message_oneof()->::clarifai::api::utils::TestProto2::MergeFrom(
          from._internal_message_oneof());
      break;
    }
    case ONE_OF_FIELD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:clarifai.api.utils.TestProto)
}

inline void TestProto::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.image_bytes_){}
    , decltype(_impl_.value_){0}
    , decltype(_impl_.one_of_field_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.image_bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.image_bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_one_of_field();
}

TestProto::~TestProto() {
  // @@protoc_insertion_point(destructor:clarifai.api.utils.TestProto)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TestProto::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
  _impl_.message_.Destroy();
  _impl_.image_bytes_.Destroy();
  if (has_one_of_field()) {
    clear_one_of_field();
  }
}

void TestProto::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TestProto::clear_one_of_field() {
// @@protoc_insertion_point(one_of_clear_start:clarifai.api.utils.TestProto)
  switch (one_of_field_case()) {
    case kStringOneof: {
      _impl_.one_of_field_.string_oneof_.Destroy();
      break;
    }
    case kBoolOneof: {
      // No need to clear
      break;
    }
    case kMessageOneof: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.one_of_field_.message_oneof_;
      }
      break;
    }
    case ONE_OF_FIELD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ONE_OF_FIELD_NOT_SET;
}


void TestProto::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.utils.TestProto)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _impl_.image_bytes_.ClearToEmpty();
  _impl_.value_ = 0;
  clear_one_of_field();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestProto::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.utils.TestProto.id"));
        } else
          goto handle_unusual;
        continue;
      // string message = 2 [(.clarifai.api.utils.cl_show_if_empty) = true, (.clarifai.api.utils.cl_moretags) = "protos are cool"];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.utils.TestProto.message"));
        } else
          goto handle_unusual;
        continue;
      // double value = 3 [(.clarifai.api.utils.cl_default_float) = 1];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // bytes image_bytes = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_image_bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string string_oneof = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_string_oneof();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.utils.TestProto.string_oneof"));
        } else
          goto handle_unusual;
        continue;
      // bool bool_oneof = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 48)) {
          _internal_set_bool_oneof(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .clarifai.api.utils.TestProto2 message_oneof = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_message_oneof(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestProto::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.utils.TestProto)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.utils.TestProto.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // string message = 2 [(.clarifai.api.utils.cl_show_if_empty) = true, (.clarifai.api.utils.cl_moretags) = "protos are cool"];
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.utils.TestProto.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // double value = 3 [(.clarifai.api.utils.cl_default_float) = 1];
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = this->_internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(3, this->_internal_value(), target);
  }

  // bytes image_bytes = 4;
  if (!this->_internal_image_bytes().empty()) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_image_bytes(), target);
  }

  // string string_oneof = 5;
  if (_internal_has_string_oneof()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_string_oneof().data(), static_cast<int>(this->_internal_string_oneof().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.utils.TestProto.string_oneof");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_string_oneof(), target);
  }

  // bool bool_oneof = 6;
  if (_internal_has_bool_oneof()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(6, this->_internal_bool_oneof(), target);
  }

  // .clarifai.api.utils.TestProto2 message_oneof = 7;
  if (_internal_has_message_oneof()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::message_oneof(this),
        _Internal::message_oneof(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.utils.TestProto)
  return target;
}

size_t TestProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.utils.TestProto)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // string message = 2 [(.clarifai.api.utils.cl_show_if_empty) = true, (.clarifai.api.utils.cl_moretags) = "protos are cool"];
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // bytes image_bytes = 4;
  if (!this->_internal_image_bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_image_bytes());
  }

  // double value = 3 [(.clarifai.api.utils.cl_default_float) = 1];
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = this->_internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    total_size += 1 + 8;
  }

  switch (one_of_field_case()) {
    // string string_oneof = 5;
    case kStringOneof: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_string_oneof());
      break;
    }
    // bool bool_oneof = 6;
    case kBoolOneof: {
      total_size += 1 + 1;
      break;
    }
    // .clarifai.api.utils.TestProto2 message_oneof = 7;
    case kMessageOneof: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.one_of_field_.message_oneof_);
      break;
    }
    case ONE_OF_FIELD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestProto::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TestProto::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestProto::GetClassData() const { return &_class_data_; }


void TestProto::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TestProto*>(&to_msg);
  auto& from = static_cast<const TestProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.utils.TestProto)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_image_bytes().empty()) {
    _this->_internal_set_image_bytes(from._internal_image_bytes());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_value = from._internal_value();
  uint64_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  switch (from.one_of_field_case()) {
    case kStringOneof: {
      _this->_internal_set_string_oneof(from._internal_string_oneof());
      break;
    }
    case kBoolOneof: {
      _this->_internal_set_bool_oneof(from._internal_bool_oneof());
      break;
    }
    case kMessageOneof: {
      _this->_internal_mutable_message_oneof()->::clarifai::api::utils::TestProto2::MergeFrom(
          from._internal_message_oneof());
      break;
    }
    case ONE_OF_FIELD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestProto::CopyFrom(const TestProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.utils.TestProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestProto::IsInitialized() const {
  return true;
}

void TestProto::InternalSwap(TestProto* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.image_bytes_, lhs_arena,
      &other->_impl_.image_bytes_, rhs_arena
  );
  swap(_impl_.value_, other->_impl_.value_);
  swap(_impl_.one_of_field_, other->_impl_.one_of_field_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestProto::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto[0]);
}

// ===================================================================

class TestProto2::_Internal {
 public:
};

TestProto2::TestProto2(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:clarifai.api.utils.TestProto2)
}
TestProto2::TestProto2(const TestProto2& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TestProto2* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.flip_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_id().empty()) {
    _this->_impl_.id_.Set(from._internal_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.flip_ = from._impl_.flip_;
  // @@protoc_insertion_point(copy_constructor:clarifai.api.utils.TestProto2)
}

inline void TestProto2::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.id_){}
    , decltype(_impl_.flip_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TestProto2::~TestProto2() {
  // @@protoc_insertion_point(destructor:clarifai.api.utils.TestProto2)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TestProto2::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.id_.Destroy();
}

void TestProto2::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TestProto2::Clear() {
// @@protoc_insertion_point(message_clear_start:clarifai.api.utils.TestProto2)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.flip_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TestProto2::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "clarifai.api.utils.TestProto2.id"));
        } else
          goto handle_unusual;
        continue;
      // bool flip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.flip_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TestProto2::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:clarifai.api.utils.TestProto2)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_id().data(), static_cast<int>(this->_internal_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "clarifai.api.utils.TestProto2.id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_id(), target);
  }

  // bool flip = 2;
  if (this->_internal_flip() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_flip(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:clarifai.api.utils.TestProto2)
  return target;
}

size_t TestProto2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:clarifai.api.utils.TestProto2)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string id = 1;
  if (!this->_internal_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_id());
  }

  // bool flip = 2;
  if (this->_internal_flip() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TestProto2::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TestProto2::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TestProto2::GetClassData() const { return &_class_data_; }


void TestProto2::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TestProto2*>(&to_msg);
  auto& from = static_cast<const TestProto2&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:clarifai.api.utils.TestProto2)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_flip() != 0) {
    _this->_internal_set_flip(from._internal_flip());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TestProto2::CopyFrom(const TestProto2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:clarifai.api.utils.TestProto2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TestProto2::IsInitialized() const {
  return true;
}

void TestProto2::InternalSwap(TestProto2* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.id_, lhs_arena,
      &other->_impl_.id_, rhs_arena
  );
  swap(_impl_.flip_, other->_impl_.flip_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TestProto2::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_getter, &descriptor_table_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto_once,
      file_level_metadata_proto_2fclarifai_2fapi_2futils_2ftest_5fproto_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace utils
}  // namespace api
}  // namespace clarifai
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::clarifai::api::utils::TestProto*
Arena::CreateMaybeMessage< ::clarifai::api::utils::TestProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::utils::TestProto >(arena);
}
template<> PROTOBUF_NOINLINE ::clarifai::api::utils::TestProto2*
Arena::CreateMaybeMessage< ::clarifai::api::utils::TestProto2 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::clarifai::api::utils::TestProto2 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
